language: node_js
node_js:
  - '6'
  #- '4' # npm 3's flat tree is needed because some packages do not
         # declare their deps correctly (e.g. chartist-plugin-tooltip)

cache: yarn

# Use containers.
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
