language: node_js
node_js:
  - 12

# Use containers.
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
addons:
  apt:
    packages:
      - qemu-utils
      - blktap-utils
      - vmdk-stream-converter

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - wget https://dl.min.io/server/minio/release/linux-amd64/minio

cache:
  yarn: true

script:
  - yarn run travis-tests
