language: node_js
node_js:
  #- stable # disable for now due to an issue of indirect dep upath with Node 9
  - 8
  - 6

# Use containers.
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
addons:
  apt:
    packages:
    - qemu-utils
    - blktap-utils

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

script:
  - yarn run test
  - yarn run test-integration
