# Example XO-Server configuration.

# This file is automatically looking for at the following places:
# - `$HOME/.config/xo-server/config.yaml`
# - `/etc/xo-server/config.yaml`
#
# The first entries have priority.

# Note: paths are relative to the configuration file.

#=====================================================================

# It may be necessary to run XO-Server as a privileged user (e.g.
# `root`) for instance to allow the HTTP server to listen on a
# [privileged ports](http://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html).
#
# To avoid security issues, XO-Server can drop its privileges by
# changing the user and the group is running with.
#
# Note: XO-Server will change them just after reading the
# configuration.

# User to run XO-Server as.
#
# Note: The user can be specified using either its name or its numeric
# identifier.
#
# Default: undefined
#user: 'nobody'

# Group to run XO-Server as.
#
# Note: The group can be specified using either its name or its
# numeric identifier.
#
# Default: undefined
#group: 'nogroup'

#=====================================================================

# Configuration of the embedded HTTP server.
http:

  # Hosts & ports on which to listen.
  #
  # By default, the server listens on 0.0.0.0:80.
  listen:
    # Basic HTTP.
    -
      # Address on which the server is listening on.
      #
      # Sets it to '127.0.0.1' to listen only on the local host.
      #
      # Default: '0.0.0.0' (all addresses)
      #hostname: '127.0.0.1'

      # Port on which the server is listening on.
      #
      # Default: undefined
      port: 80

      # Instead of `host` and `port` a path to a UNIX socket may be
      # specified (overrides `host` and `port`).
      #
      # Default: undefined
      #socket: './http.sock'

    # Basic HTTPS.
    #
    # You can find the list of possible options there https://nodejs.org/docs/latest/api/tls.html#tls.createServer
    # -
    #   # The only difference is the presence of the certificate and the
    #   # key.
    #   #
    #   #hostname: '127.0.0.1'
    #   port: 443

    #   # File containing the certificate (PEM format).
    #
    #   # If a chain of certificates authorities is needed, you may bundle
    #   # them directly in the certificate.
    #   #
    #   # Note: the order of certificates does matter, your certificate
    #   # should come first followed by the certificate of the above
    #   # certificate authority up to the root.
    #   #
    #   # Default: undefined
    #   cert: './certificate.pem'

    #   # File containing the private key (PEM format).
    #   #
    #   # If the key is encrypted, the passphrase will be asked at
    #   # server startup.
    #   #
    #   # Default: undefined
    #   key: './key.pem'

  # If set to true, all HTTP traffic will be redirected to the first
  # HTTPs configuration.
  #redirectToHttps: true

  # List of files/directories which will be served.
  mounts:
    #'/': '/path/to/xo-web/dist/'

  # List of proxied URLs (HTTP & WebSockets).
  proxies:
    # '/any/url': 'http://localhost:54722'

# HTTP proxy configuration used by xo-server to fetch resources on the
# Internet.
#
# See: https://github.com/TooTallNate/node-proxy-agent#maps-proxy-protocols-to-httpagent-implementations
#httpProxy: 'http://jsmith:qwerty@proxy.lan:3128'

#=====================================================================

# Connection to the Redis server.
redis:
    # Syntax: redis://[db[:password]@]hostname[:port]
    #
    # Default: redis://localhost:6379
    #uri: ''

# Directory containing the database of XO.
# Currently used for logs.
#
# Default: '/var/lib/xo-server/data'
#datadir: '/var/lib/xo-server/data'
