# List of skipped methods
blockedList = [
  'acl.get',
  'acl.getCurrentPermissions',
  'audit.checkIntegrity',
  'audit.generateFingerprint',
  'audit.getRecords',
  'backupNg.getAllJobs',
  'backupNg.getAllLogs',
  'cloud.getResourceCatalog',
  'cloudConfig.getAll',
  'group.getAll',
  'host.stats',
  'ipPool.getAll',
  'job.getAll',
  'log.get',
  'metadataBackup.getAllJobs',
  'plugin.get',
  'pool.listMissingPatches',
  'proxy.getAll',
  'remote.getAll',
  'remote.getAllInfo',
  'resourceSet.getAll',
  'role.getAll',
  'schedule.getAll',
  'server.getAll',
  'sr.getUnhealthyVdiChainsLength',
  'sr.stats',
  'system.getMethodsInfo',
  'system.getServerTimezone',
  'system.getServerVersion',
  'user.getAll',
  'vm.stats',
  'xo.getAllObjects',
  'xoa.supportTunnel.getState',
  'xosan.checkSrCurrentState',
  'xosan.getVolumeInfo',
]
